version: '3.8'

services:
  # Django App
  web:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8083"
    volumes:
      - .:/GENAI
    ports:
      - "8085:8083"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1

  # PostgreSQL Database (if you're using PostgreSQL)
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_db
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

  # Adminer (Database Admin Tool, optional)
  adminer:
    image: adminer
    ports:
      - "8083:8083"

# Volumes
volumes:
  postgres_data:


